In [1]:
import torch
import numpy as np

In [2]:
# torch from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
# print((x_data))

np_array = np.array(data)
np_tensor = torch.tensor(np_array)
# print(np_tensor)

# ones_like and rand_like
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)#not implemented for long
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9091, 0.5040],
        [0.7099, 0.7983]])


In [3]:
print(torch.rand((2,3,)))
print(torch.ones((2,3,)))
print(torch.zeros((3,2,)))

# comma signifies that we are unsure about shape, and might change later, or we might append additional dim

tensor([[0.6044, 0.8938, 0.8998],
        [0.0658, 0.4936, 0.9355]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
dummy1 = torch.rand((2,3,), dtype=torch.float)
print(dummy1)
print(f"shape  {dummy1.shape}")
print(f"Datatype {dummy1.dtype}")
print(f"Stored on {dummy1.device}")

tensor([[0.8794, 0.2149, 0.4621],
        [0.4481, 0.5115, 0.9042]])
shape  torch.Size([2, 3])
Datatype torch.float32
Stored on cpu


In [5]:
d2 = torch.tensor([True, False, True], dtype=torch.bool)
print(d2.dtype)

torch.bool


In [19]:
tensor = torch.rand((3, 4))
print(tensor)

tensor([[0.8662, 0.8943, 0.0527, 0.0945],
        [0.2352, 0.0788, 0.9521, 0.1025],
        [0.4749, 0.2703, 0.9077, 0.0678]])


In [20]:
print(tensor[:,0]) # first column
print(tensor[:,-1]) # last column
tensor[0,:] = 0 # first row
print(tensor[0,:]) # first row

tensor([0.8662, 0.2352, 0.4749])
tensor([0.0945, 0.1025, 0.0678])
tensor([0., 0., 0., 0.])


In [21]:
t1 = torch.cat((tensor, tensor), dim=0) # concatenate along row
print(t1)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.2352, 0.0788, 0.9521, 0.1025],
        [0.4749, 0.2703, 0.9077, 0.0678],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.2352, 0.0788, 0.9521, 0.1025],
        [0.4749, 0.2703, 0.9077, 0.0678]])


In [26]:
tensor.matmul(tensor.T) # matrix multiplication
tensor@tensor.T

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.9785, 1.0042],
        [0.0000, 1.0042, 1.1272]])

In [27]:
tensor.mul(tensor)
tensor*tensor

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0553, 0.0062, 0.9064, 0.0105],
        [0.2255, 0.0731, 0.8240, 0.0046]])

In [32]:
t2 = (tensor.sum()).item()
type(t2)

float

In [34]:
tensor.add_(5) # in place addition

tensor([[5.0000, 5.0000, 5.0000, 5.0000],
        [5.4705, 5.1576, 6.9041, 5.2050],
        [5.9498, 5.5406, 6.8155, 5.1356]])

In [37]:
k = np.ones((2,3))
print(k)
k = torch.from_numpy(k)
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
