In [1]:
import torch
import numpy as np

In [2]:
# torch from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
# print((x_data))

np_array = np.array(data)
np_tensor = torch.tensor(np_array)
# print(np_tensor)

# ones_like and rand_like
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)#not implemented for long
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6368, 0.5993],
        [0.6041, 0.0479]])


In [3]:
print(torch.rand((2,3,)))
print(torch.ones((2,3,)))
print(torch.zeros((3,2,)))

# comma signifies that we are unsure about shape, and might change later, or we might append additional dim

tensor([[0.4264, 0.8980, 0.8199],
        [0.8432, 0.9355, 0.5029]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
dummy1 = torch.rand((2,3,), dtype=torch.float)
print(dummy1)
print(f"shape  {dummy1.shape}")
print(f"Datatype {dummy1.dtype}")
print(f"Stored on {dummy1.device}")

tensor([[0.9407, 0.4856, 0.7086],
        [0.3963, 0.9009, 0.1210]])
shape  torch.Size([2, 3])
Datatype torch.float32
Stored on cpu


In [5]:
d2 = torch.tensor([True, False, True], dtype=torch.bool)
print(d2.dtype)

torch.bool


In [6]:
tensor = torch.rand((3, 4))
print(tensor)

tensor([[0.9257, 0.5599, 0.7753, 0.0085],
        [0.3920, 0.1725, 0.9617, 0.9117],
        [0.6290, 0.0846, 0.0807, 0.4739]])


In [7]:
print(tensor[:,0]) # first column
print(tensor[:,-1]) # last column
tensor[0,:] = 0 # first row
print(tensor[0,:]) # first row

tensor([0.9257, 0.3920, 0.6290])
tensor([0.0085, 0.9117, 0.4739])
tensor([0., 0., 0., 0.])


In [8]:
t1 = torch.cat((tensor, tensor), dim=0) # concatenate along row
print(t1)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.3920, 0.1725, 0.9617, 0.9117],
        [0.6290, 0.0846, 0.0807, 0.4739],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.3920, 0.1725, 0.9617, 0.9117],
        [0.6290, 0.0846, 0.0807, 0.4739]])


In [14]:
print(tensor.matmul(tensor.T)) # matrix multiplication
print(tensor@tensor.T)

tensor([[100.0000, 112.1891, 106.3406],
        [112.1891, 126.3178, 119.3005],
        [106.3406, 119.3005, 113.3150]])
tensor([[100.0000, 112.1891, 106.3406],
        [112.1891, 126.3178, 119.3005],
        [106.3406, 119.3005, 113.3150]])


In [10]:
tensor.mul(tensor)
tensor*tensor

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.1536, 0.0297, 0.9248, 0.8313],
        [0.3956, 0.0072, 0.0065, 0.2246]])

In [11]:
t2 = (tensor.sum()).item()
type(t2)

float

In [12]:
tensor.add_(5) # in place addition

tensor([[5.0000, 5.0000, 5.0000, 5.0000],
        [5.3920, 5.1725, 5.9617, 5.9117],
        [5.6290, 5.0846, 5.0807, 5.4739]])

In [13]:
k = np.ones((2,3))
print(k)
k = torch.from_numpy(k)
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
