In [15]:
import torch
import numpy as np

In [16]:
# torch from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
# print((x_data))

np_array = np.array(data)
np_tensor = torch.tensor(np_array)
# print(np_tensor)

# ones_like and rand_like
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)#not implemented for long
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8908, 0.9962],
        [0.0643, 0.2912]])


In [17]:
print(torch.rand((2,3,)))
print(torch.ones((2,3,)))
print(torch.zeros((3,2,)))

# comma signifies that we are unsure about shape, and might change later, or we might append additional dim

tensor([[0.7928, 0.2468, 0.9636],
        [0.1248, 0.0805, 0.1822]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [18]:
dummy1 = torch.rand((2,3,), dtype=torch.float)
print(dummy1)
print(f"shape  {dummy1.shape}")
print(f"Datatype {dummy1.dtype}")
print(f"Stored on {dummy1.device}")

tensor([[0.7896, 0.0110, 0.6379],
        [0.5124, 0.4171, 0.4546]])
shape  torch.Size([2, 3])
Datatype torch.float32
Stored on cpu


In [19]:
d2 = torch.tensor([True, False, True], dtype=torch.bool)
print(d2.dtype)

torch.bool


In [20]:
tensor = torch.rand((3, 4))
print(tensor)

tensor([[0.3777, 0.7713, 0.4196, 0.5054],
        [0.2182, 0.7770, 0.6709, 0.6269],
        [0.2350, 0.8521, 0.3089, 0.6820]])


In [21]:
print(tensor[:,0]) # first column
print(tensor[:,-1]) # last column
tensor[0,:] = 0 # first row
print(tensor[0,:]) # first row

tensor([0.3777, 0.2182, 0.2350])
tensor([0.5054, 0.6269, 0.6820])
tensor([0., 0., 0., 0.])


In [22]:
t1 = torch.cat((tensor, tensor), dim=0) # concatenate along row
print(t1)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.2182, 0.7770, 0.6709, 0.6269],
        [0.2350, 0.8521, 0.3089, 0.6820],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.2182, 0.7770, 0.6709, 0.6269],
        [0.2350, 0.8521, 0.3089, 0.6820]])


In [23]:
print(tensor.matmul(tensor.T)) # matrix multiplication
print(tensor@tensor.T)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 1.4944, 1.3481],
        [0.0000, 1.3481, 1.3418]])
tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 1.4944, 1.3481],
        [0.0000, 1.3481, 1.3418]])


In [24]:
tensor.mul(tensor)
tensor*tensor

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0476, 0.6038, 0.4501, 0.3930],
        [0.0552, 0.7261, 0.0954, 0.4652]])

In [25]:
t2 = (tensor.sum()).item()
type(t2)

float

In [26]:
tensor.add_(5) # in place addition

tensor([[5.0000, 5.0000, 5.0000, 5.0000],
        [5.2182, 5.7770, 5.6709, 5.6269],
        [5.2350, 5.8521, 5.3089, 5.6820]])

In [27]:
k = np.ones((2,3))
print(k)
k = torch.from_numpy(k)
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [34]:
x = torch.rand((2,3,), dtype = torch.float64)*10
x

tensor([[8.5023, 7.0575, 0.6336],
        [3.8908, 8.9794, 2.0687]], dtype=torch.float64)

In [37]:
import math

# common functions
a = torch.rand(2, 4)
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.linalg.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.9404, 0.9850, 0.8475, 0.5491],
        [0.3845, 0.7353, 0.2087, 0.2399]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [0.3845, 0.5000, 0.2087, 0.2399]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.4497, 0.6604],
        [0.0562, 0.5291]])
tensor([[1.3492, 1.9811],
        [0.1685, 1.5873]])
torch.return_types.linalg_svd(
U=tensor([[-0.8451, -0.5346],
        [-0.5346,  0.8451]]),
S=tensor([2.8068, 0.6441]),
Vh=tensor([[-0.4383, -0.8988],
        [-0.8988,  0.4383]]))
