In [5]:
import torch
import numpy as np

In [6]:
# torch from list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
# print((x_data))

np_array = np.array(data)
np_tensor = torch.tensor(np_array)
# print(np_tensor)

# ones_like and rand_like
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)#not implemented for long
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.4696, 0.5304],
        [0.0981, 0.3168]])


In [22]:
print(torch.rand((2,3,)))
print(torch.ones((2,3,)))
print(torch.zeros((3,2,)))

# comma signifies that we are unsure about shape, and might change later, or we might append additional dim

tensor([[0.9306, 0.8114, 0.8024],
        [0.9823, 0.9788, 0.7027]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [35]:
dummy1 = torch.rand((2,3,), dtype=torch.float)
print(dummy1)
print(f"shape  {dummy1.shape}")
print(f"Datatype {dummy1.dtype}")
print(f"Stored on {dummy1.device}")

tensor([[0.6760, 0.6845, 0.5474],
        [0.7995, 0.4479, 0.4021]])
shape  torch.Size([2, 3])
Datatype torch.float32
Stored on cpu


In [39]:
d2 = torch.tensor([True, False, True], dtype=torch.bool)
print(d2.dtype)

torch.bool
